kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-full-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-full-access
subjects:
- kind: User
  name: marianleica@lesformidables.club
